### ISSUE TITLE
Fatal error: Class labels are missing from the model description

### ISSUE THREAD

**Issue by chamcham115** [ultralytics/yolo-ios-app#10]
I have a question.

When I was compiled using iphone15 simulator, Compile is successfully. 
But I launched application using simulator, I got the error message in below:

Fatal error: Class labels are missing from the model description

This error was made in this source:

        guard let classLabels = mlModel.modelDescription.classLabels as? [String] else {
            fatalError("Class labels are missing from the model description")
        }

I made the "coreml". So i got the yolov8m.mlpackage. 

Can I need other file about classlabel?
the model is basic model in your application using yolo.

**Comment by chamcham115** [comment]
I solved this problem. 
It need to apply the nms, int8 option when I convert to coreml. 
Thanks.

**Comment by glenn-jocher** [comment]
@chamcham115 great to hear you've solved the issue! Applying NMS and int8 options can indeed be crucial during the CoreML conversion process. If you need further assistance or have more questions, feel free to ask. Happy coding! 😊👍
