### ISSUE TITLE
How to convert input images when I select the front camera?

### ISSUE THREAD

**Issue by chamcham115** [ultralytics/yolo-ios-app#15]
I changed the input camera from back camera to front camera. 
But Bounding Box's coordinate is outputed as flipped. 

How to correct the Bounding box coordinate?
or How to flip the input image?

**Comment by chamcham115** [comment]
I solved the problem. 
I convert to rect.origin.x coordinates. 
I flipped the this coordinates. 

Thanks.

**Comment by pderrenger** [comment]
Great to hear you've solved the issue! 🎉 Flipping the `rect.origin.x` coordinates is a smart approach when adjusting for the front camera's mirrored output. If you have any more questions or run into any other challenges, feel free to reach out. Happy coding!
