### ISSUE TITLE
Error while installing on IPad

### ISSUE THREAD

**Issue by ProfessorHT** [ultralytics/yolo-ios-app#21]
Hello,

I have accomplished the installation of the application on my iPhone without encountering any issues. However, upon attempting to install it on an iPad, I encountered a specific error. Despite the successful completion of the build process, the installation process fails, citing an error related to the one-time initialization function for the 'mlModel' within the 'viewcontroller' file.

**System Details:**
- Macbook Pro 
- Operating System: MacOS Sonoma
- Xcode Version: 15

I would greatly appreciate any guidance or assistance in resolving this issue.

Thank you in advance for your help.

**Comment by pderrenger** [comment]
@ProfessorHT hello!

Thank you for reaching out. It looks like you might be facing an issue specific to the iPad's hardware compatibility or a configuration detail within Xcode.

Here are a couple of steps you can try:
1. Ensure that your iPad’s OS version supports the deployment target set in your Xcode project. 
2. Check the device-specific settings under your project's target in Xcode - sometimes, specific configurations need to be adjusted for iPad.

If the issue persists, it could be helpful to check the initialization code in the 'viewcontroller' file. Make sure that the 'mlModel' is being loaded correctly and all necessary resources are available at runtime.

If you haven't done so yet, consider consulting the [Ultralytics Docs](https://docs.ultralytics.com) for any similar known issues or additional troubleshooting tips. 📚

Best of luck, and do let the community know how it goes!
