### ISSUE TITLE
custom model

### ISSUE THREAD

**Issue by pythonsus** [ultralytics/yolo-ios-app#28]
[Archive.zip](https://github.com/user-attachments/files/15594815/Archive.zip)
converted my best.pt file from training into a .mlpackage using the code below and when I run it I get I`YOLO/ViewController.swift:221: Fatal error: Class labels are missing from the model description`(Archive.zip has the best.pt file and best.mlpackage). 

 ```from ultralytics import YOLO
model = YOLO(f"/content/runs/detect/train/weights/best.pt")
model.export(format="coreml", int8=True, imgsz=[224, 224],data="/content/dataset/faces-10/data.yaml")```

**Comment by pythonsus** [comment]
nvm i fixed it, I forgot nms=true

**Comment by pderrenger** [comment]
@pythonsus great to hear that you resolved the issue! If you have any more questions or need further assistance in the future, feel free to reach out. Happy coding! 🚀
