### ISSUE TITLE
Ultralytics branding color palette

### ISSUE THREAD

**Issue by ambitious-octopus** [ultralytics/yolo-ios-app#39]
@john-rocky  We need to adjust the app colors to match Ultralytics branding.

Here are the colors we need to use:
https://github.com/ultralytics/ultralytics/blob/5d479c73c2933fa5020632e1b2d5b77220dce156/ultralytics/utils/plotting.py#L34-L85

**Comment by john-rocky** [comment]
@ambitious-octopus 
Changed the colors of the segment mask and detection box to the same Ultralytics color palette as the Python version.
Also removed the central focus square.
![IMG_3268](https://github.com/user-attachments/assets/3261e2d2-a841-4530-a080-1d0872501393)
