### ISSUE TITLE
The share/screenshot button doesn't work properly!

### ISSUE THREAD

**Issue by ambitious-octopus** [ultralytics/yolo-ios-app#46]
![image](https://github.com/user-attachments/assets/4ce7c3cc-5be8-46b6-9511-f7343725ee26)

@john-rocky The share/screenshot button shown in the figure does not work properly. We need the image to stop when the button is pressed to clearly show the user what they are sharing!

**Comment by john-rocky** [comment]
@ambitious-octopus 
A preview is now displayed when sharing screenshots.
https://github.com/ultralytics/yolo-ios-app/pull/47
<img src=https://github.com/user-attachments/assets/b5e1a5fc-3979-4f26-bd1d-27fa0943c943 width=200>
